import type { User, Offer, Comment, Notification, Category } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Ana García',
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
    reputationScore: 320,
    badgesCount: 4,
  },
  {
    id: 'u2',
    name: 'Carlos Romero',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    reputationScore: 180,
    badgesCount: 2,
  },
  {
    id: 'u3',
    name: 'Laura Soto',
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    reputationScore: 95,
    badgesCount: 1,
  },
];

export const MOCK_CURRENT_USER: User = {
  id: 'me',
  name: 'Javier López',
  avatarUrl: 'https://i.pravatar.cc/150?img=8',
  reputationScore: 210,
  badgesCount: 3,
};

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'o1',
    title: 'Frutas y Verduras',
    description: '50% de descuento en todas las frutas y verduras frescas',
    businessName: 'SuperMercado Central',
    isVerifiedBusiness: true,
    currentPrice: 6.45,
    previousPrice: 12.90,
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400',
    category: 'grocery',
    distance: 300,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    validations: 12,
    invalidations: 0,
    commentsCount: 3,
    postedBy: MOCK_USERS[0],
  },
  {
    id: 'o2',
    title: 'Vitamina C 1000mg',
    description: 'Lleva 3 paga 2 - Vitaminas y suplementos',
    businessName: 'Farmacia Popular',
    isVerifiedBusiness: true,
    currentPrice: 30.00,
    previousPrice: 45.00,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
    category: 'beauty',
    distance: 500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
    validations: 8,
    invalidations: 0,
    commentsCount: 1,
    postedBy: MOCK_USERS[1],
  },
  {
    id: 'o3',
    title: 'Pizza Familiar',
    description: 'Compra 1 pizza familiar y lleva gaseosa 2L gratis',
    businessName: 'Pizzería Bella',
    isVerifiedBusiness: false,
    currentPrice: 49.90,
    previousPrice: 58.00,
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    category: 'food',
    distance: 800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 30).toISOString(),
    validations: 3,
    invalidations: 0,
    commentsCount: 5,
    postedBy: MOCK_USERS[2],
  },
  {
    id: 'o4',
    title: 'Pan Francés',
    description: '$0.50 cada uno - Válido después de las 18h',
    businessName: 'Panadería del Barrio',
    isVerifiedBusiness: true,
    currentPrice: 0.50,
    previousPrice: 0.80,
    imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=400',
    category: 'food',
    distance: 200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 1).toISOString(),
    validations: 15,
    invalidations: 0,
    commentsCount: 0,
    postedBy: MOCK_USERS[0],
  },
  {
    id: 'o5',
    title: 'Zapatillas running — liquidación',
    description: 'Liquidación de temporada, todas las tallas disponibles',
    businessName: 'SportCity',
    isVerifiedBusiness: false,
    currentPrice: 39.00,
    previousPrice: 89.00,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    category: 'sports',
    distance: 1200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    expiresAt: null,
    validations: 5,
    invalidations: 0,
    commentsCount: 0,
    postedBy: MOCK_USERS[1],
  },
];

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  o1: [
    {
      id: 'c1',
      offerId: 'o1',
      text: 'Lo compré esta mañana, confirmo que sigue en oferta.',
      author: MOCK_USERS[1],
      createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    },
    {
      id: 'c2',
      offerId: 'o1',
      text: '¡Gracias por avisar! Muy buena oferta.',
      author: MOCK_USERS[2],
      createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
  ],
  o3: [
    {
      id: 'c3',
      offerId: 'o3',
      text: 'El menú también incluye postre hoy.',
      author: MOCK_USERS[0],
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
  ],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'offer_validated',
    message: 'Tu oferta "Pollo entero" recibió 5 validaciones.',
    offerId: 'o1',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'n2',
    type: 'comment_received',
    message: 'Carlos comentó en tu oferta "Pollo entero".',
    offerId: 'o1',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'n3',
    type: 'offer_expiring',
    message: 'Tu oferta "Menú del día" expira en 7 horas.',
    offerId: 'o3',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];

export const MOCK_CATEGORIES: Array<{ id: Category | 'all'; label: string; icon?: string }> = [
  { id: 'all', label: 'Todos' },
  { id: 'grocery', label: 'Mercado', icon: 'cart-outline' },
  { id: 'beauty', label: 'Farmacia', icon: 'medkit-outline' },
  { id: 'food', label: 'Comida', icon: 'restaurant-outline' },
  { id: 'other', label: 'Tiendas', icon: 'storefront-outline' },
  { id: 'electronics', label: 'Electrónica', icon: 'phone-portrait-outline' },
  { id: 'fashion', label: 'Moda', icon: 'shirt-outline' },
  { id: 'sports', label: 'Deportes', icon: 'football-outline' },
  { id: 'home', label: 'Hogar', icon: 'home-outline' },
];

export const MOCK_MY_OFFERS: Offer[] = [MOCK_OFFERS[0], MOCK_OFFERS[2]];
