import type { User, Offer, Comment, Notification, Category } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Ana García',
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
    reputationScore: 320,
    badgesCount: 4,
  },
  {
    id: 'u2',
    name: 'Carlos Romero',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    reputationScore: 180,
    badgesCount: 2,
  },
  {
    id: 'u3',
    name: 'Laura Soto',
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    reputationScore: 95,
    badgesCount: 1,
  },
];

export const MOCK_CURRENT_USER: User = {
  id: 'me',
  name: 'Javier López',
  avatarUrl: 'https://i.pravatar.cc/150?img=8',
  reputationScore: 210,
  badgesCount: 3,
};

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'o1',
    headline: '50% en frutas y verduras',
    description: 'Oferta válida en toda la sección de frescos',
    businessName: 'SuperMercado Central',
    isVerifiedBusiness: true,
    category: 'grocery',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400',
    pricing: { type: 'percentage', percentage: 50 },
    distanceMeters: 300,
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    confirmationsCount: 12,
    invalidationsCount: 0,
    commentsCount: 3,
    postedBy: MOCK_USERS[0],
  },
  {
    id: 'o2',
    headline: '2x1 en pizzas familiares',
    businessName: 'Pizzería Bella',
    isVerifiedBusiness: false,
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400',
    pricing: { type: 'bundle', label: '2x1' },
    distanceMeters: 800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 30).toISOString(),
    confirmationsCount: 8,
    invalidationsCount: 1,
    commentsCount: 5,
    postedBy: MOCK_USERS[2],
  },
  {
    id: 'o3',
    headline: 'Happy hour de 18 a 20',
    description: 'Cervezas y tragos a mitad de precio',
    businessName: 'Bar El Rincón',
    isVerifiedBusiness: false,
    category: 'food',
    imageUrl: null,
    pricing: { type: 'text', label: 'Bebidas al 50%' },
    distanceMeters: 450,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
    confirmationsCount: 21,
    invalidationsCount: 0,
    commentsCount: 7,
    postedBy: MOCK_USERS[1],
  },
  {
    id: 'o4',
    headline: 'Pan francés precio de tarde',
    businessName: 'Panadería del Barrio',
    isVerifiedBusiness: true,
    category: 'food',
    imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=400',
    pricing: { type: 'price', currentPrice: 900, previousPrice: 1500 },
    distanceMeters: 200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 1).toISOString(),
    confirmationsCount: 15,
    invalidationsCount: 0,
    commentsCount: 0,
    postedBy: MOCK_USERS[0],
  },
  {
    id: 'o5',
    headline: '30% pagando en efectivo',
    businessName: 'SportCity',
    isVerifiedBusiness: false,
    category: 'sports',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    pricing: { type: 'percentage', percentage: 30 },
    distanceMeters: 1200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    expiresAt: null,
    confirmationsCount: 5,
    invalidationsCount: 0,
    commentsCount: 0,
    postedBy: MOCK_USERS[1],
  },
  {
    id: 'o6',
    headline: 'Lleva 3 paga 2 en vitaminas',
    businessName: 'Farmacia Popular',
    isVerifiedBusiness: true,
    category: 'beauty',
    imageUrl: null,
    pricing: { type: 'bundle', label: '3x2' },
    distanceMeters: 500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
    confirmationsCount: 6,
    invalidationsCount: 0,
    commentsCount: 1,
    postedBy: MOCK_USERS[2],
  },
  {
    id: 'o7',
    headline: '2da unidad al 50%',
    description: 'En toda la línea de electrónica',
    businessName: 'Electro Casa',
    isVerifiedBusiness: true,
    category: 'electronics',
    imageUrl: null,
    pricing: { type: 'bundle', label: '2da al 50%' },
    distanceMeters: 700,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    expiresAt: null,
    confirmationsCount: 3,
    invalidationsCount: 0,
    commentsCount: 2,
    postedBy: MOCK_USERS[0],
  },
];

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  o1: [
    {
      id: 'c1',
      offerId: 'o1',
      text: 'Lo compré esta mañana, confirmo que sigue en oferta.',
      author: MOCK_USERS[1],
      createdAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    },
    {
      id: 'c2',
      offerId: 'o1',
      text: '¡Gracias por avisar! Muy buena oferta.',
      author: MOCK_USERS[2],
      createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
  ],
  o2: [
    {
      id: 'c3',
      offerId: 'o2',
      text: 'El menú también incluye postre hoy.',
      author: MOCK_USERS[0],
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
  ],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'offer_validated',
    message: 'Tu oferta "50% en frutas" recibió 5 validaciones.',
    offerId: 'o1',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'n2',
    type: 'comment_received',
    message: 'Carlos comentó en tu oferta "2x1 en pizzas".',
    offerId: 'o2',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'n3',
    type: 'offer_expiring',
    message: 'Tu oferta "Happy hour" expira en 3 horas.',
    offerId: 'o3',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];

export const MOCK_CATEGORIES: Array<{ id: Category | 'all'; label: string; icon?: string }> = [
  { id: 'all', label: 'Todos' },
  { id: 'grocery', label: 'Mercado', icon: 'cart-outline' },
  { id: 'beauty', label: 'Farmacia', icon: 'medkit-outline' },
  { id: 'food', label: 'Comida', icon: 'restaurant-outline' },
  { id: 'other', label: 'Tiendas', icon: 'storefront-outline' },
  { id: 'electronics', label: 'Electrónica', icon: 'phone-portrait-outline' },
  { id: 'fashion', label: 'Moda', icon: 'shirt-outline' },
  { id: 'sports', label: 'Deportes', icon: 'football-outline' },
  { id: 'home', label: 'Hogar', icon: 'home-outline' },
];

export const MOCK_MY_OFFERS: Offer[] = [MOCK_OFFERS[0], MOCK_OFFERS[1]];
